### ISSUE TITLE
problème avec l'onglet  GitHub manquant

### ISSUE THREAD

**Issue by GuyliannEngels** [Ndounkang/mauricecarlos-ndounkang-blog#1]
Salut @Ndounkang ,

Je reprends ton mail afin de structurer notre discussion dans une ISSUE. Voici ton mail

Bonjour Monsieur
j'ai vraiment besoin de vous
j'ai fini la rédaction de mon article 1 mais du coup je n'arrive pas a la mettre en ligne, puisque dans le Rstudios, je trouve pas la fenêtre git pour commit. Bien vouloir vérifier je vous en pris

merci

**Comment by GuyliannEngels** [comment]
Je pense que tu n'es tout simplement pas dans le projet lié au blog

**Comment by Ndounkang** [comment]
je vérifie actuellement

**Comment by Ndounkang** [comment]
je viens de me connecter dans une autre machine mais je trouve mon article modifié la fois passée

**Comment by GuyliannEngels** [comment]
Je ne comprends pas ton problème. Essaye d'être un peu plus explicite

**Comment by Ndounkang** [comment]
je n'ai pas accès a mon article a partir d'une autre machine, pour temps je viens de cloner

**Comment by Ndounkang** [comment]
lorsque je clone ce message apparait
>>> git clone --progress https://github.com/Ndounkang/mauricecarlos-ndounkang-blog.git mauricecarlos-ndounkang-blog
fatal: destination path 'mauricecarlos-ndounkang-blog' already exists and is not an empty directon

**Comment by GuyliannEngels** [comment]
Ce message t'informe que tu ne peux pas cloner un dépot que tu as déjà cloner tout simplement

**Comment by GuyliannEngels** [comment]
Si tu n'as pas accès à ton artcile c'est que tu n as pas fait de commit sur l'autre pc

**Comment by Ndounkang** [comment]
bien évidemment je n'avais pas fait, je suis rentré sur le même pc et je me suis fait aidé par une camarade, a présent je peut faire le pull et le push 

excusé moi, j'ai seconde question, comment remplacer l'image de l'éléphant par notre image.merci

**Comment by Ndounkang** [comment]
Monsieur, je n'arrive pas mettre mon image en ligne

**Comment by GuyliannEngels** [comment]
Tu dois inserer ton image tout simplement comme le requiert le language markdown

```
![](path)
```

**Comment by GuyliannEngels** [comment]
si j'ai répondu à tes questions n'hésite pas à fermer l'issue
