### ISSUE TITLE
actualiser lesdonnées

### ISSUE THREAD

**Issue by Ndounkang** [Ndounkang/mauricecarlos-ndounkang-blog#2]
salut 
@GuyliannEngels

**Comment by GuyliannEngels** [comment]
Salut, 

Quelle est ton problème ?

**Comment by Ndounkang** [comment]
j'arrive pas a actualiser les données pour faire les devoirs, je réalise pull, on me demande de commit

**Comment by Ndounkang** [comment]
ceci est ce qu'on affiche,
>>> git pull
error: Your local changes to the following files would be overwritten by merge:
	_posts/2019-09-18-article-1/article-1.Rmd
	_posts/2019-09-18-article-1/article-1.html
	_posts/2019-11-04-article-2/article-2.Rmd
	_posts/2019-11-04-article-2/article-2.html
	docs/index.html
	docs/posts/2019-09-18-article-1/index.html
	docs/posts/posts.json
	docs/sitemap.xml
Please commit your changes or stash them before you merge.
Aborting
Updating 49a04fc..0ac4497

**Comment by Ndounkang** [comment]
je sais où se trouve le conflit mais ça pourra modifier l'article en ligne puisque dans cette machine se trouvent les modifications de depuis la semaine derniere

**Comment by Ndounkang** [comment]
si je fait le commit, je dois donc selectionner les les fichiers? puis que je ne le fait pas de peur d'aller modifier en ligne

**Comment by Ndounkang** [comment]
Bonjour Monsieur,                                              j’aurai besoin du lien (projet) pour les analyses statistiques comme promis.                            Bien à vous
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : mercredi 13 novembre 2019 16:32:33
À : Ndounkang/mauricecarlos-ndounkang-blog <mauricecarlos-ndounkang-blog@noreply.github.com>
Cc : Maurice Carlos NDOUNKANG <MauriceCarlos.NDOUNKANG@student.umons.ac.be>; Author <author@noreply.github.com>
Objet : Re: [Ndounkang/mauricecarlos-ndounkang-blog] actualiser lesdonnées (#2)


Salut,

Quelle est ton problème ?

**Comment by GuyliannEngels** [comment]
voici maurice, un lien de travail

https://classroom.github.com/g/LBegi5Rh

Bonne journée

UMONS
___________________________________
Guyliann Engels
Assistant/ Research and teaching assistant
Université de Mons / University of Mons
Service d'Ecologie numérique des milieux aquatiques / Numerical Ecology of Aquatic Systems Laboratory
6, Avenue du Champ de Mars, Pentagone, 3D21
7000 Mons
+32(0)65/37 34 78




Le 17 nov. 2019 à 10:00, Ndounkang <notifications@github.com<mailto:notifications@github.com>> a écrit :

Bonjour Monsieur, j’aurai besoin du lien (projet) pour les analyses statistiques comme promis. Bien à vous
________________________________
De : Guyliann Engels <notifications@github.com<mailto:notifications@github.com>>
Envoyé : mercredi 13 novembre 2019 16:32:33
À : Ndounkang/mauricecarlos-ndounkang-blog <mauricecarlos-ndounkang-blog@noreply.github.com<mailto:mauricecarlos-ndounkang-blog@noreply.github.com>>
Cc : Maurice Carlos NDOUNKANG <MauriceCarlos.NDOUNKANG@student.umons.ac.be<mailto:MauriceCarlos.NDOUNKANG@student.umons.ac.be>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [Ndounkang/mauricecarlos-ndounkang-blog] actualiser lesdonnées (#2)


Salut,

Quelle est ton problème ?
