### ISSUE TITLE
Problème avec disqus

### ISSUE THREAD

**Issue by GuyliannEngels** [Ndounkang/mauricecarlos-ndounkang-blog#4]
Salut @Ndounkang ,

Il semble que tu éprouves des difficultés avec ton blog. Est ce que tu peux m'en dire plus dans cette issue ?

**Comment by Ndounkang** [comment]
Salut @GuyliannEngels 

En faite , j'ai pus régler le problème en partant de vos articles. juste quelques lignes de code qui manquaient.
Merci Beaucoup

**Comment by GuyliannEngels** [comment]
Bravo @Ndounkang :)
